/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface_Grafica;
import Programa.ActionListiners.*;
import Programa.Sistema.SistemaDoGerenciadorFinanceiro;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author emanu
 */
public class Tela extends javax.swing.JFrame {
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        SistemaDoGerenciadorFinanceiro sistema = new SistemaDoGerenciadorFinanceiro();
        try{
            sistema.recuperarDados();
            JOptionPane.showMessageDialog(this, "Sistema recuperado com sucesso");
        }catch(IOException e){
            e.getStackTrace();
        }
        ImageIcon carteiraImg = new ImageIcon("./img/carteira.png");
        painelPrincipal = new javax.swing.JPanel();
        painelInformativo = new javax.swing.JPanel();
        nomeDoUsuario = new javax.swing.JLabel();
        saldoDoUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel(carteiraImg);
        painelInformativoDeEntradas = new javax.swing.JPanel();
        tituloEntradas = new javax.swing.JLabel();
        saldoDeEntradas = new javax.swing.JLabel();
        valorDasEntradas = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tituloSaidas = new javax.swing.JLabel();
        saldoDeSaidas = new javax.swing.JLabel();
        valorDasSaidas = new javax.swing.JLabel();
        barraDeMenu = new javax.swing.JMenuBar();
        menuRegistrar = new javax.swing.JMenu();
        registrarEntrada = new javax.swing.JMenuItem();
        registrarSaida = new javax.swing.JMenuItem();
        menuPesquisar = new javax.swing.JMenu();
        pesquisarTodasAsEntradas = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        pesquisarEntradaPorCodigo = new javax.swing.JMenuItem();
        pesquisarSaidaPorCodigo = new javax.swing.JMenuItem();
        menuOutro = new javax.swing.JMenu();
        apagarDados = new javax.swing.JMenuItem();
        salvarDados = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        painelPrincipal.setBackground(new java.awt.Color(51, 51, 51));

        painelInformativo.setBackground(new java.awt.Color(102, 102, 102));

        nomeDoUsuario.setText(sistema.getNomeDoUsuario()+" ");

        saldoDoUsuario.setText(String.valueOf(sistema.calcularSaldo())+" R$");

        javax.swing.GroupLayout painelInformativoLayout = new javax.swing.GroupLayout(painelInformativo);
        painelInformativo.setLayout(painelInformativoLayout);
        painelInformativoLayout.setHorizontalGroup(
            painelInformativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInformativoLayout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addGroup(painelInformativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nomeDoUsuario)
                    .addComponent(saldoDoUsuario))
                .addGap(368, 368, 368))
        );
        painelInformativoLayout.setVerticalGroup(
            painelInformativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInformativoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(nomeDoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saldoDoUsuario)
                .addGap(20, 20, 20))
        );

        jLabel1.setText(null);

        painelInformativoDeEntradas.setBackground(new java.awt.Color(102, 102, 102));

        tituloEntradas.setText("Quantidade De Entradas");

        saldoDeEntradas.setText(String.valueOf(sistema.getValorDeTodasAsEntradas()));

        valorDasEntradas.setText(String.valueOf(sistema.getEntradasDoUsuario().size()));

        javax.swing.GroupLayout painelInformativoDeEntradasLayout = new javax.swing.GroupLayout(painelInformativoDeEntradas);
        painelInformativoDeEntradas.setLayout(painelInformativoDeEntradasLayout);
        painelInformativoDeEntradasLayout.setHorizontalGroup(
            painelInformativoDeEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInformativoDeEntradasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tituloEntradas)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelInformativoDeEntradasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelInformativoDeEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(valorDasEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saldoDeEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );
        painelInformativoDeEntradasLayout.setVerticalGroup(
            painelInformativoDeEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInformativoDeEntradasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloEntradas)
                .addGap(24, 24, 24)
                .addComponent(saldoDeEntradas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valorDasEntradas)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        tituloSaidas.setText("Quantidade De Saídas");

        saldoDeSaidas.setText(String.valueOf(sistema.getValorDeTodasAsSaidas()));

        valorDasSaidas.setText(String.valueOf(sistema.getSaidasDoUsuario().size()));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tituloSaidas)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valorDasSaidas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saldoDeSaidas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(tituloSaidas)
                .addGap(18, 18, 18)
                .addComponent(saldoDeSaidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valorDasSaidas)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelInformativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelInformativoDeEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(125, 125, 125))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelInformativoDeEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(painelInformativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(painelPrincipal);

        barraDeMenu.setBorder(null);

        menuRegistrar.setText("Registrar");

        registrarEntrada.setText("Registrar Entrada");
        registrarEntrada.addActionListener(new RegistrarEntradaAction(sistema, this));

        menuRegistrar.add(registrarEntrada);

        registrarSaida.setText("Registrar Saída");
        registrarSaida.addActionListener(new RegistrarSaidaAction(sistema, this));
        menuRegistrar.add(registrarSaida);

        barraDeMenu.add(menuRegistrar);

        menuPesquisar.setText("Pesquisa");

        pesquisarTodasAsEntradas.setText("Pesquisar Entradas");
        pesquisarTodasAsEntradas.addActionListener(new PesquisarTodasAsEntradasAction(sistema, this));
        menuPesquisar.add(pesquisarTodasAsEntradas);

        jMenuItem2.setText("Pesquisar Saidas");
        menuPesquisar.add(jMenuItem2);

        pesquisarEntradaPorCodigo.setText("Pesquisar Entradas Por Código");
        pesquisarEntradaPorCodigo.addActionListener(new PesquisarEntradaPorCodigo(sistema, this));
        menuPesquisar.add(pesquisarEntradaPorCodigo);

        pesquisarSaidaPorCodigo.setText("Pesquisar Saidas Por Código ");
        menuPesquisar.add(pesquisarSaidaPorCodigo);

        barraDeMenu.add(menuPesquisar);

        menuOutro.setText("Outros");
//        menuOutro.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                menuOutroActionPerformed(evt);
//            }
//        });

        apagarDados.setText("Apagar Dados");
        apagarDados.addActionListener(new ApagarDadosAction(sistema, this));
        menuOutro.add(apagarDados);

        salvarDados.setText("Salvar Dados");
        salvarDados.addActionListener(new SalvarDadosAction(sistema, this));
        menuOutro.add(salvarDados);

        barraDeMenu.add(menuOutro);

        setJMenuBar(barraDeMenu);

        pack();
        setLocationRelativeTo(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem apagarDados;
    private javax.swing.JMenuBar barraDeMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuOutro;
    private javax.swing.JMenu menuPesquisar;
    private javax.swing.JMenu menuRegistrar;
    private javax.swing.JLabel nomeDoUsuario;
    private javax.swing.JPanel painelInformativo;
    private javax.swing.JPanel painelInformativoDeEntradas;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JMenuItem pesquisarEntradaPorCodigo;
    private javax.swing.JMenuItem pesquisarSaidaPorCodigo;
    private javax.swing.JMenuItem pesquisarTodasAsEntradas;
    private javax.swing.JMenuItem registrarEntrada;
    private javax.swing.JMenuItem registrarSaida;
    private javax.swing.JLabel saldoDeEntradas;
    private javax.swing.JLabel saldoDeSaidas;
    private javax.swing.JLabel saldoDoUsuario;
    private javax.swing.JMenuItem salvarDados;
    private javax.swing.JLabel tituloEntradas;
    private javax.swing.JLabel tituloSaidas;
    private javax.swing.JLabel valorDasEntradas;
    private javax.swing.JLabel valorDasSaidas;
    // End of variables declaration//GEN-END:variables
}
